### ISSUE TITLE
mvn package does not complete successfully 

### ISSUE THREAD

**Issue by niloofar-razavi** [lanoxx/masterylearning#32]
When using commit b7bcfa9be53b2c4c1062a8766c0b7e10ac2159ea and newer running mvn package fails with:

> smartlecture-client@0.7.4 release /home/niloofar/git/masterylearning_2/client
> NODE_ENV='production' webpack --config webpack.prod.js -p

module.js:549
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/nodejs/webpack/bin/webpack.js:16:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smartlecture-client@0.7.4 release: `NODE_ENV='production' webpack --config webpack.prod.js -p`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smartlecture-client@0.7.4 release script.

**Comment by lanoxx** [comment]
I just verified this and I can successfully build with `mvn` on my machine. I just realized that the `release` goal under npm scripts does not depend on `npm ci` or `npm install`. So, I am taking a wild guess here, but it could be that your dependencies are no up-to-date. Running `npm ci` which is like `npm install` but will leave the `package-lock.json` unchanged should fix this, if not then I will need to take a closer look.

I pushed `0854a9f86ea9373edec32f8ddc360996f20f1ecf` which should fix this issue assuming my analysis is correct.

Please reopen if this did not fix the issue.
